#!/bin/sh

# script/run Run the test suite for the application. Optionally pass in a path
# to an individual test file to run a single test. Also calls script/test to
# run lints.

set -e

cd "$(dirname "$0")/.."

if [ -n "$DEBUG" ]; then
	set -x
fi

TEST_FILE=$1

if [ -n "$TEST_FILE" ]; then
	KATA_NAME=$(basename "${TEST_FILE}" | cut -f 1 -d '.')
	echo "==> Running ${KATA_NAME}..."
	phpdbg -qrr ./vendor/bin/kahlan --spec="$TEST_FILE"
else
	echo "===> Run all katas..."
	phpdbg -qrr ./vendor/bin/kahlan
fi

./script/test
